/** 预置文案项：展示给运营看的名称 + 程序内键名（键名不在界面上展示） */

export type MiniappStringPreset = { key: string; label: string };

export const MINIAPP_STRING_PRESETS: Partial<Record<string, MiniappStringPreset[]>> = {
  "pages/home/home": [{ key: "welcomeTip", label: "首页提示条" }],
  "pages/mall/mall": [
    { key: "mallSubtitle", label: "商城顶部副标题" },
    { key: "mallHeroTip", label: "商城紫色区域说明文字" },
  ],
  "pages/shops/shops": [{ key: "shopsHeadTip", label: "网点列表顶部提示" }],
  "pages/vip-center/vip-center": [
    { key: "titleNotOpen", label: "未开通 VIP 时 · 主标题" },
    { key: "subNotOpen", label: "未开通 VIP 时 · 副说明" },
    { key: "paySuffix", label: "未达标时 · 付费开通提示（接在副说明后面）" },
    { key: "titleSuper", label: "超管账号 · 权益标题" },
    { key: "subSuper", label: "超管账号 · 权益说明" },
    { key: "titleVipActive", label: "已开通 VIP · 默认主标题" },
  ],
  "pages/share-app/share-app": [{ key: "shareHeadline", label: "邀请页主标题" }],
  "pages/merchant-wallet/merchant-wallet": [{ key: "walletHeadTip", label: "资金页顶部提示" }],
  "pages/partner-wallet/partner-wallet": [{ key: "commissionHeadTip", label: "佣金页顶部提示" }],
  "pages/profile/profile": [
    { key: "profileSlogan", label: "我的页标语（头像下）" },
    { key: "profileSectionServicesTitle", label: "板块标题 · 常用服务" },
    { key: "profileSvcTracksIcon", label: "常用服务 · 行车记录 · 图标（1～2字或表情）" },
    { key: "profileSvcTracksName", label: "常用服务 · 行车记录 · 名称" },
    { key: "profileSvcAlarmIcon", label: "常用服务 · 防盗报警 · 图标" },
    { key: "profileSvcAlarmName", label: "常用服务 · 防盗报警 · 名称" },
    { key: "profileSvcFenceIcon", label: "常用服务 · 电子围栏 · 图标" },
    { key: "profileSvcFenceName", label: "常用服务 · 电子围栏 · 名称" },
    { key: "profileSvcAuthIcon", label: "常用服务 · 授权管理 · 图标" },
    { key: "profileSvcAuthName", label: "常用服务 · 授权管理 · 名称" },
    { key: "profileSectionMallTitle", label: "板块标题 · 智控商城与升级" },
    { key: "profileMallEntryIcon", label: "智控商城 · 图标" },
    { key: "profileMallEntryName", label: "智控商城 · 名称" },
    { key: "profileShopsEntryIcon", label: "升级网点 · 图标" },
    { key: "profileShopsEntryName", label: "升级网点 · 名称" },
    { key: "profileSectionPartnerTitle", label: "板块标题 · 合作与拓展" },
    { key: "profilePartnerInviteIcon", label: "合作 · 邀请好友 · 图标" },
    { key: "profilePartnerInviteName", label: "合作 · 邀请好友 · 名称" },
    { key: "profilePartnerApplyIcon", label: "合作 · 合作商申请 · 图标" },
    { key: "profilePartnerApplyName", label: "合作 · 合作商申请 · 名称" },
    { key: "profilePartnerMgmtIcon", label: "合作 · 后台管理 · 图标" },
    { key: "profilePartnerMgmtName", label: "合作 · 后台管理 · 名称" },
    { key: "profilePartnerSuperIcon", label: "合作 · 绑定管理 · 图标" },
    { key: "profilePartnerSuperName", label: "合作 · 绑定管理 · 名称" },
    { key: "profileSectionSystemTitle", label: "板块标题 · 系统" },
    { key: "profileSysLoginIcon", label: "系统 · 登录账号 · 图标" },
    { key: "profileSysLoginTitle", label: "系统 · 登录账号 · 标题" },
    { key: "profileSysAccountIcon", label: "系统 · 账号设置 · 图标" },
    { key: "profileSysAccountTitle", label: "系统 · 账号设置 · 标题" },
    { key: "profileSysNotifyIcon", label: "系统 · 通知设置 · 图标" },
    { key: "profileSysNotifyTitle", label: "系统 · 通知设置 · 标题" },
    { key: "profileSysLogoutIcon", label: "系统 · 退出登录 · 图标" },
    { key: "profileSysLogoutTitle", label: "系统 · 退出登录 · 标题" },
  ],
};
