import type { AdminWithdrawalReviewRow } from "../types/gatewayStore";

/** 与 device-gateway defaultWithdrawalReviewSeed 演示数据对齐（未连网关时的默认行） */
export function defaultWithdrawalReviewSeed(): AdminWithdrawalReviewRow[] {
  return [
    {
      id: "seed_wr_partner_pending",
      kind: "partner",
      status: "pending",
      applicantPhone: "13800001001",
      applicantName: "陈强",
      applicantRoleHint: "合作商主管",
      partnerRootPhone: "13800001001",
      partnerRootName: "华南体系",
      amountYuan: 1200,
      createdAt: "2026-04-30 10:12:00",
      payoutChannel: "wechat_wallet",
      payoutSummary: "微信零钱 · 演示账户",
      payPipeline: "manual",
      walletAuditSnapshot: {
        accruedLifetimeYuan: 4520,
        availableYuanAtApply: 2200,
        withdrawnPaidYuan: 800,
        pendingOutYuanAtApply: 520,
      },
    },
    {
      id: "seed_wr_merchant_pending",
      kind: "merchant",
      status: "pending",
      applicantPhone: "13900001001",
      applicantName: "海淀·极客电动车改装",
      applicantRoleHint: "升级网点商家",
      partnerRootPhone: "13800001001",
      partnerRootName: "华南体系（渠道归属演示）",
      amountYuan: 800,
      createdAt: "2026-05-01 09:00:00",
      payoutChannel: "wechat_wallet",
      payoutSummary: "微信零钱 · 对公法人同名（演示）",
      walletAuditSnapshot: {
        accruedLifetimeYuan: 960,
        availableYuanAtApply: 800,
        withdrawnPaidYuan: 0,
        pendingOutYuanAtApply: 160,
      },
    },
    {
      id: "seed_wr_paid_done",
      kind: "partner",
      status: "paid",
      applicantPhone: "13800001002",
      applicantName: "刘洋",
      applicantRoleHint: "合作商主管",
      partnerRootPhone: "13800001002",
      partnerRootName: "华北体系",
      amountYuan: 560.5,
      createdAt: "2026-04-28 14:20:00",
      resolvedAt: "2026-04-29 11:00:00",
      payoutChannel: "bank",
      payoutSummary: "对公账户 6222 **** 801",
      paidAt: "2026-04-29",
      transferChannel: "对公转账",
      transferRefNo: "BOC-DEMO-202604290001",
      operatorNote: "已核对营业执照与账户名一致",
      lastOperator: "平台财务（演示）",
    },
  ];
}
